import type { Invoice } from '@/lib/types/invoice'
import { InvoiceHeader } from './invoice-header'
import { InvoiceItemsTable } from './invoice-items-table'
import { InvoiceNotes } from './invoice-notes'
import { InvoicePrintButton } from './invoice-print-button'
import { InvoiceSummary } from './invoice-summary'

interface InvoiceViewProps {
  invoice: Invoice
}

export function InvoiceView({ invoice }: InvoiceViewProps) {
  return (
    <div className="animate-in fade-in space-y-8 duration-1000">
      <div className="flex justify-end print:hidden">
        <InvoicePrintButton />
      </div>

      <div className="border-muted/30 shadow-primary/5 bg-card relative space-y-10 overflow-hidden rounded-2xl border p-10 shadow-2xl sm:p-16">
        {/* Decorative corner accent */}
        <div className="bg-primary/5 pointer-events-none absolute top-0 right-0 -mt-16 -mr-16 h-32 w-32 rounded-bl-full" />

        <InvoiceHeader
          invoice={{
            title: invoice.title,
            clientName: invoice.clientName,
            issueDate: invoice.issueDate,
            dueDate: invoice.dueDate,
            status: invoice.status,
            senderName: invoice.senderName,
            senderContact: invoice.senderContact,
          }}
        />

        <div className="py-2">
          <InvoiceItemsTable items={invoice.items} />
        </div>

        <InvoiceSummary
          subtotal={invoice.subtotal}
          taxRate={invoice.taxRate}
          taxAmount={invoice.taxAmount}
          total={invoice.total}
        />

        {invoice.notes && (
          <div className="border-muted/50 border-t pt-8">
            <InvoiceNotes notes={invoice.notes} />
          </div>
        )}

        <div className="text-muted-foreground/40 pt-12 text-center text-[10px] font-bold tracking-widest uppercase">
          Generated by Notion Invoice Manager
        </div>
      </div>
    </div>
  )
}
